class_name UpgradeList
## GENERATED by tools/gen_upgrades.gd — DO NOT HAND-EDIT.
##
## Explicit preloads rather than a DirAccess scan: directory listings
## misbehave inside an exported .pck (resources gain .remap suffixes), so
## the pool would silently shrink on the web build only.
##
## Regenerate:
##   <console.exe> --headless --path . -s res://tools/gen_upgrades.gd

const ALL: Array[UpgradeResource] = [
	preload("res://resources/upgrades/aegis.tres"),
	preload("res://resources/upgrades/barrage.tres"),
	preload("res://resources/upgrades/cadence.tres"),
	preload("res://resources/upgrades/cannonball.tres"),
	preload("res://resources/upgrades/carapace.tres"),
	preload("res://resources/upgrades/chain_lightning.tres"),
	preload("res://resources/upgrades/cryo_rounds.tres"),
	preload("res://resources/upgrades/draft_lance.tres"),
	preload("res://resources/upgrades/draft_orbital.tres"),
	preload("res://resources/upgrades/draft_scattergun.tres"),
	preload("res://resources/upgrades/event_horizon.tres"),
	preload("res://resources/upgrades/executioner.tres"),
	preload("res://resources/upgrades/flechette_storm.tres"),
	preload("res://resources/upgrades/focus.tres"),
	preload("res://resources/upgrades/fusillade.tres"),
	preload("res://resources/upgrades/greed.tres"),
	preload("res://resources/upgrades/honed_edge.tres"),
	preload("res://resources/upgrades/magnetism.tres"),
	preload("res://resources/upgrades/momentum.tres"),
	preload("res://resources/upgrades/nova_orbit.tres"),
	preload("res://resources/upgrades/orbit_count.tres"),
	preload("res://resources/upgrades/orbit_speed.tres"),
	preload("res://resources/upgrades/overclock.tres"),
	preload("res://resources/upgrades/overdrive.tres"),
	preload("res://resources/upgrades/pierce.tres"),
	preload("res://resources/upgrades/prism_core.tres"),
	preload("res://resources/upgrades/rapid_fire.tres"),
	preload("res://resources/upgrades/refraction.tres"),
	preload("res://resources/upgrades/relentless.tres"),
	preload("res://resources/upgrades/reservoir.tres"),
	preload("res://resources/upgrades/ricochet.tres"),
	preload("res://resources/upgrades/scatter.tres"),
	preload("res://resources/upgrades/scholar.tres"),
	preload("res://resources/upgrades/second_wind.tres"),
	preload("res://resources/upgrades/sharp_shots.tres"),
	preload("res://resources/upgrades/shop_coils.tres"),
	preload("res://resources/upgrades/shop_hollow.tres"),
	preload("res://resources/upgrades/shop_mirror.tres"),
	preload("res://resources/upgrades/singularity.tres"),
	preload("res://resources/upgrades/siphon.tres"),
	preload("res://resources/upgrades/split_shot.tres"),
	preload("res://resources/upgrades/swift_boots.tres"),
	preload("res://resources/upgrades/tough_hide.tres"),
	preload("res://resources/upgrades/twin_fangs.tres"),
	preload("res://resources/upgrades/velocity.tres"),
]
