class_name SkillList
## GENERATED by tools/gen_skills.gd — DO NOT HAND-EDIT.
##
## Regenerate:
##   <console.exe> --headless --path . -s res://tools/gen_skills.gd

const ALL: Array[SkillNode] = [
	preload("res://resources/skills/node_card_coils.tres"),
	preload("res://resources/skills/node_card_hollow.tres"),
	preload("res://resources/skills/node_card_mirror.tres"),
	preload("res://resources/skills/node_hardy.tres"),
	preload("res://resources/skills/node_keen.tres"),
	preload("res://resources/skills/node_magnet.tres"),
	preload("res://resources/skills/node_quick.tres"),
	preload("res://resources/skills/node_scholar.tres"),
	preload("res://resources/skills/node_swift.tres"),
]
