extends Node2D
## Run orchestrator: owns run state (time, kills, xp) and wires everything.
## Children signal up; Main calls down. Nothing else knows about Main.

const ARENA: Rect2 = Rect2(0, 0, 1280, 720)

## Warm-up set for the flash shader — see _warm_up_shaders.
const FLASH_SHADER: Shader = preload("res://assets/shaders/flash.gdshader")
const WARM_TEXTURES: Array[Texture2D] = [
	preload("res://assets/sprites/enemy_drifter.png"),
	preload("res://assets/sprites/boss_core.png"),
	preload("res://assets/sprites/boss_mirror.png"),
	preload("res://assets/sprites/bolt.png"),
	preload("res://assets/sprites/bullet.png"),
]

const XP_GEM_SCENE: PackedScene = preload("res://scenes/pickups/xp_gem.tscn")
const DEATH_BURST_SCENE: PackedScene = preload("res://scenes/fx/death_burst.tscn")
const HEALTH_PICKUP_SCENE: PackedScene = preload("res://scenes/pickups/health_pickup.tscn")
const POWER_UP_SCENE: PackedScene = preload("res://scenes/pickups/power_up.tscn")

## Power-ups are the SHORT-TERM counterpart to upgrades: an upgrade changes the
## rest of the run, a power-up changes the next few seconds. Rare on purpose —
## the moment has to feel like luck, not income.
const POWER_UPS: Array[PowerUpResource] = [
	preload("res://resources/powerups/shield.tres"),
	preload("res://resources/powerups/power.tres"),
	preload("res://resources/powerups/haste.tres"),
	preload("res://resources/powerups/collect.tres"),
]
## Playtest 2026-08-02: at 1.8% a tester played to level 9 without seeing one.
## Rare should mean 'a moment', not 'a rumour'.
const POWER_UP_DROP_CHANCE: float = 0.040

## Health is a world drop, not a level-up option. Only drops when the player
## is actually hurt, so it can never be the wasted pick a heal-at-full-HP was.
const HEALTH_DROP_CHANCE: float = 0.045

## Review finding 23: this list used to be 38 hand-written preloads under a
## comment claiming they were "GENERATED by tools/gen_upgrades.gd's companion
## step". No such step existed, the comment's own "36 entries" was stale against
## 38, and the failure it warned about — a new .tres silently absent from the
## pool — was live the whole time.
##
## The companion step exists now. `resources/upgrades/upgrade_list.gd` is emitted
## by the generator from the ids it actually saved, so the list cannot disagree
## with the directory. Regenerate with:
##   <console.exe> --headless --path . -s res://tools/gen_upgrades.gd
const UPGRADE_LIST: Array[UpgradeResource] = UpgradeList.ALL

var time_survived: float = 0.0
var kills: int = 0
var total_xp: int = 0
var level: int = 1
var xp_into_level: int = 0
## id -> times taken; the pool uses this to respect stack caps.
var stacks: Dictionary = {}

var pool: UpgradePool
var run_rng: RandomNumberGenerator = RandomNumberGenerator.new()
## This run's identity. One seed drives upgrade draws, enemy choice and
## spawn placement, so replaying it reproduces the run.
var run_state: RunState
## True once victory has banked this run, so a later death in endless
## improves records without counting a second run.
var _banked: bool = false
## Every weapon that can be drafted mid-run. Only --dev-unlocks reads it: the
## real game hands these over one card at a time.
const DRAFTABLE_WEAPONS: Array[StringName] = [&"orbital", &"scattergun", &"lance"]
## True once this run has been finalised (banked + its ending logged), so the
## death path and the teardown path cannot both bank the same run.
var _ended: bool = false
## Level-ups since the last Rare-or-better. A cold streak that lasts a whole
## run is invisible in aggregate stats, so it gets a hard floor.
var _pity: int = 0

## Boss event 1 (10:00) is NOGAXEH, the hexagon mirror — the only other hexagon
## in the game, and the one place the silhouette rule is broken on purpose.
const BOSS_EVENT_MIRROR: int = 1
## Total HP of the CURRENT boss event, so one bar can describe a fight that has
## three bodies in it. Zero means no event is live.
var _boss_event_max_hp: int = 0
var _boss_event_index: int = 0
## Unlocks earned during THIS run, surfaced on the victory and game-over screens.
var _new_unlocks: Array[StringName] = []
## Re-entrancy guard for Event Horizon — see _implode.
var _imploding: bool = false

## Time-scale toggle, cycled with T (or Back on a controller).
##
## Primarily a TESTING affordance — reaching the 10:00 boss takes ten minutes, and
## iterating on it at 1x is most of a working session. Left in as a player-facing
## option because x2 is a real difficulty mode for anyone who wants one.
##
## THE GAME IS NOT BALANCED FOR x2 OR x3, deliberately. It is a raw time-scale
## multiplier: spawn rates, projectile speeds, cooldowns and the run clock all
## move together, so a "win" at x2 is a genuinely harder win and a run at x3 is a
## curiosity. Nothing is retuned to compensate and nothing should be.
const SPEED_STEPS: Array[float] = [1.0, 2.0, 3.0]
var _speed_index: int = 0

## Dev flags, read from user args after a bare `--` (same convention as
## ai_screenshot.gd). Inert in a normal run and in exported builds.
var _dev_stats: bool = false
var _dev_autopick: bool = false
var _dev_autocontinue: bool = false
var _dev_stats_t: float = 0.0
var _tele_t: float = 0.0

@onready var player: Player = $Player
@onready var spawner: Spawner = $Spawner
@onready var director: RunDirector = $RunDirector
@onready var bosses: Node2D = $Bosses
@onready var enemy_bolts: Node2D = $EnemyBolts
@onready var victory_screen: VictoryScreen = $Victory
@onready var true_ending: TrueEndingScreen = $TrueEnding
@onready var enemies: Node2D = $Enemies
@onready var pickups: Node2D = $Pickups
@onready var projectiles: Node2D = $Projectiles
@onready var level_up_panel: LevelUpPanel = $LevelUpPanel
@onready var hud: Hud = $Hud
@onready var game_over: GameOverScreen = $GameOver
@onready var pause_panel: PausePanel = $PausePanel


func _ready() -> void:
	# A reload that interrupted a hit-stop would otherwise leave the entire game
	# running at 5% speed, with nothing to ever set it back. The speed toggle
	# deliberately does NOT persist across a restart — a run should start at 1x
	# unless the player asks otherwise.
	Engine.time_scale = 1.0
	run_state = RunState.with_seed(RunState.random_seed_value())
	run_rng.seed = run_state.seed_value
	Telemetry.begin_run(run_state.seed_value)
	pool = UpgradePool.new(UPGRADE_LIST, run_rng)
	spawner.target = player
	spawner.container = enemies
	spawner.arena = ARENA
	spawner.rng = run_rng
	spawner.bolt_container = enemy_bolts
	spawner.enemy_spawned.connect(_on_enemy_spawned)
	# One RNG drives upgrades, spawn choice and spawn placement, so a seeded run
	# reproduces whole — the groundwork M3 needs for seeded runs.
	director.spawner = spawner
	director.target = player
	director.boss_container = bosses
	director.bolt_container = enemy_bolts
	director.rng = run_rng
	director.boss_spawned.connect(_on_boss_spawned)
	director.victory.connect(_on_victory)
	director.boss_event_cleared.connect(_on_boss_event_cleared)
	# The music is a CONSUMER of run intensity, not a system of its own.
	director.intensity_changed.connect(Music.set_intensity)
	# Review finding 2: `Meta.unlocked` had ZERO listeners project-wide. Unlocks
	# were earned, written to disk, and applied only on the NEXT run — so the
	# game's strongest restart hook fired in complete silence, and a player who
	# won and pressed Continue met endless without the dash they had just earned.
	Meta.unlocked.connect(_on_unlocked)
	player.died.connect(_on_player_died)
	player.second_wind.connect(_on_second_wind)
	player.hurt.connect(_on_player_hurt)
	player.health_changed.connect(hud.set_health)
	player.weapon.container = projectiles
	player.weapon.rng = run_rng
	player.scattergun.container = projectiles
	player.scattergun.rng = run_rng
	player.lance.rng = run_rng
	player.apply_unlocks(Meta.state.unlocks)
	_apply_purchases()
	level_up_panel.upgrade_chosen.connect(_on_upgrade_chosen)
	# Continuing into endless brings the layers back where they were.
	victory_screen.continued.connect(Music.resume_gameplay)
	true_ending.continued.connect(Music.resume_gameplay)
	# Auto-pause when the window loses focus. Standard QOL, and it matters
	# more here than usual: an unattended run keeps spawning and dies.
	# NOT in capture runs: the capture window opens unfocused, and the pause
	# froze the frame counter — the sheet never landed.
	if not _is_capture_run():
		get_window().focus_exited.connect(_pause_if_playing)
	hud.set_health(player.health.hp, player.health.max_hp)
	hud.set_xp(xp_into_level, Progression.xp_required(level), level)
	Music.play_gameplay()
	_apply_dev_flags()
	_warm_up_shaders()
	# P, not ESC, and said out loud at the top of every run. In a FULLSCREEN
	# browser tab the browser owns the Escape key -- it exits fullscreen and the
	# page never receives it -- so the documented pause key silently does not
	# work in the one mode a player is most likely to be in. A page cannot
	# override that, and should not be able to. The fix is to make sure the
	# player knows the other key exists before they need it.
	hud.announce("P TO PAUSE")
	print("BESTAGON boot OK — Godot %s" % Engine.get_version_info()["string"])


## Review finding 25: every enemy carries flash.gdshader's ShaderMaterial, and a
## shader program compiles LAZILY on its first draw — so the first enemy to
## appear compiled it mid-combat, plus the first texture uploads, on exactly the
## frame the player least wants a hitch. Acceptance criterion 11 is "no visible
## frame hitch on first enemy draw", and on a single-threaded web export that
## compile is the most likely place to fail it.
##
## Draws one of every material-bearing texture ONCE, with the effect ACTIVE
## (flash = 1) so the branch that actually costs something is the branch that
## gets compiled. Kept on-screen but at 1% scale and 2% alpha, because an
## off-screen sprite is culled and a culled sprite compiles nothing.
func _warm_up_shaders() -> void:
	var warm := Node2D.new()
	warm.position = player.global_position
	warm.scale = Vector2(0.01, 0.01)
	warm.modulate = Color(1.0, 1.0, 1.0, 0.02)
	add_child(warm)
	for texture: Texture2D in WARM_TEXTURES:
		var sprite := Sprite2D.new()
		sprite.texture = texture
		var mat := ShaderMaterial.new()
		mat.shader = FLASH_SHADER
		mat.set_shader_parameter(&"flash", 1.0)
		sprite.material = mat
		warm.add_child(sprite)
	await get_tree().process_frame
	await get_tree().process_frame
	warm.queue_free()


## --dev-godmode  player takes no damage
## --dev-stats    add the [meta] profile line at boot. The 30s [stats] ticker it
##                used to gate is ALWAYS on now (2026-08-03): it is the flight
##                recorder, and a recorder only dev runs carry records nothing —
##                the first remote freeze log survived the kill and still said
##                only "boot OK", because every marker was behind this flag
## --dev-autopick auto-take the first upgrade offer (a paused panel would stall
##                a headless soak run forever)
## --dev-unlocks  every weapon active regardless of the save — the only way to
##                exercise (or playtest) a gated weapon without earning it first
## --dev-noprofile  does NOTHING except trip the prefix check below, which moves
##                the save off the real profile. It exists because the gate's
##                gameplay smoke deliberately carries no other dev flag —
##                --dev-autopick takes a different level-up path and would leave
##                the panel untested — so the one run that MUST look like a real
##                run was also the one run that banked into the human's records.
##                Seven bot runs and a best time of 8.03s reached the title
##                screen that way before anyone noticed.
func _apply_dev_flags() -> void:
	# ANY dev flag moves the save off the real profile BEFORE the run can bank
	# anything into it (review finding 12). Done first, and by prefix rather than
	# by listing the flags, so a dev flag added later cannot forget to opt in.
	for arg: String in OS.get_cmdline_user_args():
		if arg.begins_with("--dev-"):
			Meta.use_dev_profile()
			player.apply_unlocks(Meta.state.unlocks)
			break
	for arg: String in OS.get_cmdline_user_args():
		match arg:
			"--dev-godmode":
				player.health.invincible = true
				print("[dev] godmode")
			"--dev-unlocks":
				# UNLOCK_DASH included. The flag whose entire purpose is
				# "exercise a gated thing without earning it" was silently
				# omitting the newest gated thing, which is how the dash would
				# have gone untested in every soak and every capture.
				player.apply_unlocks([MetaState.UNLOCK_ORBITAL,
						MetaState.UNLOCK_ELITE_HUNTER,
						MetaState.UNLOCK_ENDLESS_PROVEN, MetaState.UNLOCK_DASH])
				# ...and since M7.3 an unlock only offers a CARD, so unlocking
				# alone would leave every soak and every capture firing the
				# blaster and nothing else. Draft them too: this flag means
				# "show me all of it", not "show me the draft screen".
				for id: StringName in DRAFTABLE_WEAPONS:
					player.stats.draft_weapon(id)
				player.refresh_from_stats()
				print("[dev] all unlocks + all weapons drafted")
			"--dev-autopilot":
				player.dev_autopilot = true
				print("[dev] autopilot")
			"--dev-stats":
				_dev_stats = true
				print("[dev] stats")
			"--dev-autopick":
				_dev_autopick = true
				print("[dev] autopick")
			"--dev-autocontinue":
				_dev_autocontinue = true
				print("[dev] autocontinue")
	if _dev_stats:
		print("[meta] dir=%s runs=%d wins=%d best_time=%.0f best_kills=%d unlocks=%s"
				% [OS.get_user_data_dir(), Meta.state.runs_played, Meta.state.victories,
				Meta.state.best_time, Meta.state.best_kills, str(Meta.state.unlocks)])


## Mid-run restart needs a SECOND press of R inside this window. R sits one key
## from T (speed) on QWERTY, and with speed cycled mid-fight all run long, a
## slipped finger was a full-run wipe with no confirmation (playtest 2026-08-03:
## "game ruining"). First press arms and announces; the window then expires in
## silence, so an accident costs nothing and a real reroll costs one tap.
##
## REAL milliseconds, not game time — LevelUpPanel.PICK_LOCKOUT's reasoning: a
## human confirmation window must not shrink to a third at SPEED x3.
const RESTART_CONFIRM_MS: int = 2000
var _restart_armed_ms: int = -100000


## Input lives in _unhandled_input, not _physics_process, because a paused tree
## runs no physics — pause would be unable to un-pause itself.
func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed(&"mute"):
		get_viewport().set_input_as_handled()
		Audio.set_muted(not Audio.muted)
		if pause_panel.visible:
			pause_panel._refresh_mute()
		return
	if event.is_action_pressed(&"speed"):
		get_viewport().set_input_as_handled()
		_cycle_speed()
		return
	if event.is_action_pressed(&"restart") and not _modal_open():
		get_viewport().set_input_as_handled()
		if Time.get_ticks_msec() - _restart_armed_ms > RESTART_CONFIRM_MS:
			_restart_armed_ms = Time.get_ticks_msec()
			Sfx.play(&"click", -10.0)
			hud.announce("PRESS  R  AGAIN TO RESTART")
			return
		get_tree().paused = false
		get_tree().reload_current_scene()
		return
	if not event.is_action_pressed(&"pause"):
		return
	# Never steal the key from a screen that already owns the pause state.
	if _modal_open():
		return
	get_viewport().set_input_as_handled()
	if pause_panel.visible:
		pause_panel.resume()
	else:
		_pause_if_playing()


## Auto-pause when the window loses focus.
##
## Playtest 2026-08-03: "game unfroze after a while" in a fullscreen browser tab.
## A browser throttles or entirely stops requestAnimationFrame for a page it
## considers hidden or occluded, and Godot's web build drives its whole main loop
## from rAF -- so a tab that loses focus does not slow down, it STOPS, and then
## resumes exactly where it left off when focus returns. From the player's side
## that is indistinguishable from a freeze followed by a recovery, which is
## precisely what was reported, with no error logged anywhere because nothing
## went wrong.
##
## This cannot be prevented from inside the page and should not be. What it can
## do is make the stop DELIBERATE: pausing on focus loss turns a mysterious
## freeze into a pause screen, and stops a player being eaten while they are
## looking at something else. Desktop gets the same benefit for alt-tab.
func _notification(what: int) -> void:
	if what != NOTIFICATION_APPLICATION_FOCUS_OUT and what != NOTIFICATION_WM_WINDOW_FOCUS_OUT:
		return
	# A screenshot run is not a player. It is launched from a terminal and so
	# never holds focus, which meant this pause fired instantly and every
	# gameplay capture came back as a picture of the pause menu — silently, with
	# no error, from the day focus-pause shipped. The capture rig is how this
	# project looks at itself; it does not get to be broken by a QoL fix.
	if AiScreenshot.capturing:
		return
	# `is_node_ready` guards the notification arriving before _ready has wired
	# anything up -- focus events fire during startup on some platforms.
	if not is_node_ready() or _modal_open() or pause_panel == null or pause_panel.visible:
		return
	_pause_if_playing()


## Shove the crowd off the player when a hit lands.
##
## Playtest 2026-08-03: enemies "just latch on weirdly" after connecting. Contact
## damage grants i-frames, so an enemy that hits you then sits inside you for the
## whole invulnerable window -- dealing nothing, looking stuck, and hiding the
## fact that you are briefly safe. This gives that window a physical read: the
## hit throws everything off you, and the space it opens is the escape.
##
## Damage-free by design. It is a breather, not a weapon -- if the shove also
## hurt, taking a hit would become a crowd-control button and invert what being
## hit is supposed to mean.
##
## Applied to EVERY enemy rather than inside a radius: the point is that the
## screen visibly opens up for a moment, and a radius edge is a place where half
## a crowd lurches and the rest stands still.
const HURT_SHOVE_PIXELS: float = 75.0


func _on_player_hurt(at: Vector2) -> void:
	for node: Node in get_tree().get_nodes_in_group(&"enemies"):
		var e: Enemy = node as Enemy
		if e != null and is_instance_valid(e):
			e.shove(at, HURT_SHOVE_PIXELS)


func _is_capture_run() -> bool:
	for arg: String in OS.get_cmdline_user_args():
		if arg.begins_with("--screenshot="):
			return true
	return false


## True while another screen owns the pause. Level-up, victory and game-over all
## pause the tree themselves, and two owners of one flag is a stuck game.
func _modal_open() -> bool:
	return (level_up_panel.visible or victory_screen.visible or game_over.visible
			or true_ending.visible)


## `reason` is diagnostic, not behavioural. The focus-out path runs INSIDE the
## OS window message (Godot dispatches _notification from its WndProc), and the
## 2026-08-03 freeze dump shows the main thread blocked exactly there — inside
## user32 dispatch, under engine code, on a kernel wait. If frozen logs keep
## ending at "reason=focus", that hypothesis graduates to the fix list; a log
## that ends at "reason=key" points somewhere else entirely.
func _pause_if_playing(reason: String = "key") -> void:
	if _modal_open() or pause_panel.visible or get_tree().paused:
		return
	print("[pause] t=%.0fs reason=%s" % [time_survived, reason])
	get_tree().paused = true
	pause_panel.show_build(UPGRADE_LIST, stacks, level, time_survived, kills, player.stats)


func _physics_process(delta: float) -> void:
	# The director owns run time; Main mirrors it so there is exactly one clock.
	time_survived = director.elapsed
	run_state.elapsed = time_survived
	run_state.kills = kills
	run_state.level = level
	Telemetry.set_run_time(time_survived)
	# The 10:00 fight sizes itself against this — see RunDirector._mirror_mult.
	director.player_level = level
	_sample_telemetry(delta)
	hud.set_run(time_survived, kills)
	hud.set_dash(player.dash_ready_fraction())
	_update_boss_bar()
	_push_buffs()
	# UNCONDITIONAL since 2026-08-03 — this is the flight recorder, not a dev
	# readout. The first remote freeze report arrived as a log that had survived
	# the kill (the flush fix worked) and contained ONE line, because every print
	# except boot OK was gated behind --dev-stats and no player runs with dev
	# flags. A log that says nothing localizes nothing: the whole point of these
	# lines is that the LAST one before the log goes quiet brackets the freeze to
	# a 30-second window and says what the arena looked like. One print per 30s
	# of game time; flush-per-print is already on (project.godot).
	_dev_stats_t += delta
	if _dev_stats_t >= 30.0:
		_dev_stats_t = 0.0
		print("[stats] t=%4.0fs enemies=%3d pickups=%3d proj=%2d bolts=%3d kills=%4d lvl=%2d bosses=%d speed=x%d"
				% [time_survived, enemies.get_child_count(), pickups.get_child_count(),
				projectiles.get_child_count(), enemy_bolts.get_child_count(),
				kills, level, director.bosses_alive, int(run_speed())])


func _push_buffs() -> void:
	var entries: Array = []
	for id: StringName in player.buffs.active_ids():
		entries.append({"name": String(id).to_upper(), "left": player.buffs.remaining(id)})
	hud.set_buffs(entries)


## Every 5s: the pressure curve. Answers "is the start too easy" with numbers —
## HP fraction and living-enemy count over time, not a recollection.
func _sample_telemetry(delta: float) -> void:
	if not Telemetry.enabled:
		return
	_tele_t += delta
	if _tele_t < 5.0:
		return
	_tele_t = 0.0
	Telemetry.event(&"tick", {
		"hp": player.health.hp,
		"max_hp": player.health.max_hp,
		"kills": kills,
		"lvl": level,
		"alive": enemies.get_child_count(),
		"bosses": director.bosses_alive,
	})


func _on_enemy_spawned(enemy: Enemy) -> void:
	enemy.died.connect(_on_enemy_died)


## A boss is just a very large enemy as far as kills, XP and juice are concerned
## — except in the mix, where its arrival and death are the run's loudest beats.
func _on_boss_spawned(boss: Node2D) -> void:
	boss.died.connect(_on_enemy_died)
	boss.died.connect(_on_boss_killed)
	var mirror: Nogaxeh = boss as Nogaxeh
	if mirror != null:
		mirror.fuse_lit.connect(_on_fuse_lit)
		mirror.detonated.connect(_on_detonated)
	elif director.mirror_active():
		# EVERY Prism in the mirror event drops a guaranteed heal, and this is
		# load-bearing rather than a nicety. Healing is a world drop at 4.5% on an
		# enemy death, and nothing else spawns for the whole fight — so six kill
		# events over ~2 minutes would otherwise carry roughly a 27% chance of a
		# single 2 HP pickup. The adds do three jobs: the shield gate, the threat,
		# and the sustain, and they put the heals exactly where the design wants
		# them, right before the blast.
		boss.died.connect(func(_xp: int, at: Vector2, _tint: Color) -> void:
			_spawn_health.call_deferred(at))
	Sfx.play(&"boss_spawn", -2.0)
	player.camera.add_trauma(0.6)
	# One bar for the whole EVENT: accumulate the total the player must chew
	# through, because at 10:00 there are three bodies and three bars is noise.
	#
	# ESCORTS ARE EXCLUDED (2026-08-03). They used to add to the denominator, which
	# meant the bar titled NOGAXEH tracked 18,400 HP of which the mirror was only
	# 4,000 — so killing the two opening Prisms visibly drained "his" bar while he
	# stood shielded and untouched, and the playtest read that as the shield being
	# broken. The bar now shows the thing it is named after and nothing else; the
	# escorts announce themselves by being on screen.
	var big: Boss = boss as Boss
	if big == null or not big.is_escort:
		_boss_event_max_hp += boss.max_hp
	_announce_boss()
	Telemetry.event(&"boss_spawn", {"alive": director.bosses_alive})
	# Unconditional, like [stats]. (When first written this claimed both known
	# freezes were near boss fights; freeze #3 promptly happened at t~90-120s in
	# a near-empty arena, no boss. The marker stays — a run-beat line costs
	# nothing and still says which side of a spawn a later freeze landed on.)
	print("[boss] spawned t=%.0fs alive=%d" % [time_survived, director.bosses_alive])


## Name the thing that just arrived. The 5:00 event used to appear with a sound
## and a camera shake and nothing else — no name, no bar (review finding 3).
##
## Event 1 is NOGAXEH, the hexagon mirror. Its banner spells HEXAGON first and
## then flips, because the reveal is that the shape you have been the whole run
## is now standing opposite you, and typography lands that faster than text ever
## could.
func _announce_boss() -> void:
	if director.bosses_alive > 1:
		return  # only the first spawn of an event announces
	if _boss_event_index == BOSS_EVENT_MIRROR:
		hud.set_boss("HEXAGON", 1, 1)
		hud.flip_boss_name("HEXAGON", "NOGAXEH")
	else:
		hud.set_boss("THE PRISM", 1, 1)


## Live progress through the current boss event. Dead bosses are freed, so their
## HP simply stops being counted while the denominator stays at the event total.
func _update_boss_bar() -> void:
	if _boss_event_max_hp <= 0:
		return
	if director.bosses_alive <= 0:
		_boss_event_max_hp = 0
		_boss_event_index += 1
		hud.hide_boss()
		return
	var hp: int = 0
	var shielded: bool = false
	for child: Node in bosses.get_children():
		var boss: Boss = child as Boss
		# Escorts are excluded from the NUMERATOR for the same reason they are
		# excluded from the denominator — see _on_boss_spawned. Both halves have to
		# agree or the bar reads as full for the whole fight.
		if boss != null and boss.is_escort:
			continue
		var body: Enemy = child as Enemy
		if body != null:
			hp += maxi(0, body.hp)
		if boss != null and boss.invulnerable:
			shielded = true
	hud.boss_bar.max_value = _boss_event_max_hp
	hud.boss_bar.value = hp
	hud.set_boss_shielded(shielded,
			"NOGAXEH" if _boss_event_index == BOSS_EVENT_MIRROR else "THE PRISM")


## Applied mid-run AND announced. Both halves matter: the first is why a winner
## who continues can actually use their reward, the second is review finding 2.
func _on_unlocked(ids: Array[StringName]) -> void:
	player.apply_unlocks(Meta.state.unlocks)
	for id: StringName in ids:
		if not _new_unlocks.has(id):
			_new_unlocks.append(id)
	if ids.is_empty():
		return
	hud.announce("UNLOCKED — %s\n%s" % [
			MetaState.unlock_label(ids[0]), MetaState.unlock_blurb(ids[0])])


## Fired once, on the first boss event cleared. The reward is already banked by
## the time this runs — Continue is pure upside.
func _on_victory(_event_index: int) -> void:
	print("[victory] t=%.0fs kills=%d lvl=%d" % [time_survived, kills, level])
	# The victory screen waits on a button, which would stall a headless soak at
	# the exact moment endless begins — the part that most needs soaking.
	Telemetry.event(&"victory", {"kills": kills, "lvl": level})
	Music.play_victory()
	run_state.won = true
	_banked = true
	# Remember what this banking paid, so the endless stretch is topped up to the
	# run's real depth at the end rather than paid for twice.
	run_state.shards_banked = MetaState.shards_for(time_survived, run_state.boss_events)
	Meta.absorb_run(run_state.to_result())  # banked BEFORE the choice is offered
	if _dev_autocontinue:
		return
	get_tree().paused = true
	# absorb_run above already fired Meta.unlocked, so _new_unlocks is populated
	# by the time the screen that has to announce them is built.
	victory_screen.show_results(time_survived, kills, level, _new_unlocks)


## Fired EVERY time a boss event is cleared, where `victory` fires once per run.
## The mirror event is the run's real ending and gets its own screen; every other
## later event is just endless getting harder and says nothing.
func _on_boss_event_cleared(event_index: int) -> void:
	# Counted for EVERY event, including the ones deep in endless: the skill
	# tree's currency is depth-weighted, and this is the depth.
	run_state.boss_events += 1
	if event_index != BOSS_EVENT_MIRROR or _ended:
		return
	# `_ended` matters here: NOGAXEH dies either way, so a player killed BY the
	# detonation would otherwise be shown the game-over screen and the true
	# ending on the same frame. The blast resolves first, and a run that ended
	# has ended.
	Sfx.play(&"boss_death", 0.0)
	Music.play_victory()
	if _dev_autocontinue:
		return
	get_tree().paused = true
	true_ending.show_results(time_survived, kills, level,
			player.stats.drafted_weapons, _new_unlocks)


func _on_enemy_died(xp_value: int, at: Vector2, tint: Color) -> void:
	kills += 1
	Telemetry.event(&"kill", {"n": kills})
	if player.stats.lifesteal_chance > 0.0 and run_rng.randf() < player.stats.lifesteal_chance:
		player.health.heal(1)
	if player.stats.implode_radius > 0.0:
		_implode(at)
	if player.health.hp < player.health.max_hp and run_rng.randf() < HEALTH_DROP_CHANCE:
		_spawn_health.call_deferred(at)
	elif run_rng.randf() < POWER_UP_DROP_CHANCE:
		_spawn_power_up.call_deferred(at)
	Sfx.play(&"pop", -13.0)
	# 0.12 produced 0.086 viewport px of shake — see GameCamera. The kill beat is
	# the single most repeated moment in the game; it has to be felt at all.
	# Routed through add_kill_trauma so a forty-kill cascade is ONE big hit
	# rather than forty stacked ones, which pinned the camera and made the arena
	# unreadable at exactly the moment there was most to look at.
	player.camera.add_kill_trauma(0.22)
	# died fires from a physics callback (projectile body_entered) — adding
	# physics nodes to the tree mid-flush is forbidden, so defer the spawns.
	_spawn_gem.call_deferred(xp_value, at)
	_spawn_burst.call_deferred(at, tint)


## Event Horizon: a kill drags its neighbours inward and hurts them. The pull is
## what sells it — damage alone would just be a smaller Nova.
func _implode(at: Vector2) -> void:
	# Review finding 14. `died` is emitted SYNCHRONOUSLY inside Enemy.take_hit, so
	# this recursed: _on_enemy_died -> _implode -> take_hit -> died ->
	# _on_enemy_died -> _implode, with every level rescanning the entire enemies
	# group. Bounded by the live enemy count rather than infinite (take_hit
	# early-returns on hp <= 0), but an Event Horizon player in a 60-enemy crowd
	# triggered a deep same-frame chain of O(n^2) group scans — and endless is
	# about to get much busier. One implosion per chain: the kills all still
	# happen, they just stop each starting a cascade of their own.
	if _imploding:
		return
	_imploding = true
	var radius: float = player.stats.implode_radius
	for node: Node in get_tree().get_nodes_in_group(&"enemies"):
		var enemy: Enemy = node as Enemy
		if enemy == null:
			continue
		var offset: Vector2 = at - enemy.global_position
		var dist: float = offset.length()
		if dist > radius or dist < 0.01:
			continue
		enemy.global_position += offset.normalized() * minf(dist * 0.45, 26.0)
		enemy.take_hit(maxi(1, roundi(player.stats.damage_from(1))))
	_imploding = false


## Second Wind: the run does not end, and everything nearby pays for it.
func _on_second_wind(at: Vector2) -> void:
	Telemetry.event(&"second_wind", {})
	for node: Node in get_tree().get_nodes_in_group(&"enemies"):
		var enemy: Enemy = node as Enemy
		if enemy != null and at.distance_to(enemy.global_position) <= 260.0:
			enemy.take_hit(9999)


func _spawn_gem(xp_value: int, at: Vector2) -> void:
	var gem: XpGem = XP_GEM_SCENE.instantiate()
	gem.setup(xp_value, player)
	gem.position = at
	pickups.add_child(gem)
	gem.collected.connect(_on_gem_collected)
	if player.stats.greed:
		gem.attract(player)  # Greed: no gem is ever left behind


func _spawn_health(at: Vector2) -> void:
	var pickup: HealthPickup = HEALTH_PICKUP_SCENE.instantiate()
	pickup.setup(player)
	pickup.position = at
	pickups.add_child(pickup)
	pickup.collected.connect(func() -> void:
		player.health.heal(2)
		Sfx.play(&"health", -6.0))


func _spawn_power_up(at: Vector2) -> void:
	var choice: PowerUpResource = _pick_power_up()
	if choice == null:
		return
	# Logged on DROP as well as on collect: the ratio of the two answers "are
	# power-ups actually reachable, or are they dying on the floor?", which
	# collection events alone cannot tell you.
	Telemetry.event(&"powerup_drop", {"id": String(choice.id)})
	var pickup: PowerUp = POWER_UP_SCENE.instantiate()
	pickup.setup(choice, player)
	pickup.position = at
	pickups.add_child(pickup)
	pickup.collected.connect(_on_power_up_collected)


func _pick_power_up() -> PowerUpResource:
	var total: float = 0.0
	for p: PowerUpResource in POWER_UPS:
		total += maxf(0.0, p.weight)
	if total <= 0.0:
		return null
	var roll: float = run_rng.randf() * total
	for p: PowerUpResource in POWER_UPS:
		roll -= maxf(0.0, p.weight)
		if roll <= 0.0:
			return p
	return POWER_UPS[POWER_UPS.size() - 1]


func _on_power_up_collected(resource: PowerUpResource) -> void:
	Sfx.play(&"powerup", -6.0)
	player.camera.add_trauma(0.15)
	Telemetry.event(&"powerup_take", {"id": String(resource.id)})
	if resource.is_instant():
		_collect_all_gems()
		return
	player.buffs.grant(resource.buff_id(), resource.duration)


## The Collect power-up: every gem on the map homes in at once. Instant rather
## than timed because a "magnet for 8s" would just be a worse Magnetism upgrade.
func _collect_all_gems() -> void:
	for child: Node in pickups.get_children():
		if child is XpGem:
			(child as XpGem).attract(player)


func _spawn_burst(at: Vector2, tint: Color, power: float = 1.0) -> void:
	var burst: CPUParticles2D = DEATH_BURST_SCENE.instantiate()
	burst.setup(tint, power)
	burst.position = at
	pickups.add_child(burst)


## The run's loudest beat, and review finding 7. Killing a boss used to fire the
## generic enemy-death payload plus one extra sound: identical trauma, identical
## 12-particle burst sized for a 12px chaser. This is a 32px boss that took a
## minute, and on the first event it is the moment the player WINS.
func _on_boss_killed(_xp_value: int, at: Vector2, tint: Color) -> void:
	Sfx.play(&"boss_death", -2.0)
	player.camera.add_trauma(0.95)
	_spawn_burst.call_deferred(at, tint, 3.4)
	_hitstop(0.11)


## The phase-4 shield is broken and NOGAXEH is stunned, charging. Five seconds to
## kill it or get clear — it dies either way, and the clock only decides whether
## the player eats the blast.
func _on_fuse_lit(seconds: float) -> void:
	# Unconditional breadcrumb, like [boss]. The finale is REACHABLE ONLY through
	# phase 4, so an overpowered player who deletes NOGAXEH early never sees it —
	# and the log could not previously tell "the fuse is broken" from "the fight
	# ended before the fuse could exist". Playtest 2026-08-03 asked exactly that
	# ("does final boss charge up to explode still? didn't see it").
	print("[fuse] lit t=%.0fs hp=%d/%d" % [time_survived, player.health.hp, player.health.max_hp])
	hud.announce("NOGAXEH IS OVERLOADING\n%d SECONDS" % int(seconds))
	Music.set_intensity(3)
	player.camera.add_trauma(0.7)
	Telemetry.event(&"fuse_lit", {"hp": player.health.hp, "max_hp": player.health.max_hp})


## The blast. Damage is a PERCENTAGE OF THE PLAYER'S MAX HP, so stacking HP
## cannot trivialise the finale — a player who arrives above half survives it and
## a player who arrives hurt does not, which is what makes the attrition of the
## middle phases matter.
##
## Routed through Player.apply_damage like every other source, so Second Wind,
## the shield buff and the hurt cue all behave exactly as they do anywhere else.
## The one thing it ignores is i-frames' usual mercy: it clears them first, or a
## player who was clipped by a bolt in the last half second would walk through
## the explosion untouched by an accident of timing.
func _on_detonated(at: Vector2) -> void:
	var core: bool = player.global_position.distance_to(at) <= Nogaxeh.BLAST_CORE
	var fraction: float = Nogaxeh.BLAST_CORE_FRACTION if core else Nogaxeh.BLAST_EDGE_FRACTION
	var amount: int = maxi(1, roundi(float(player.health.max_hp) * fraction))
	player.clear_invuln()
	player.apply_damage(amount, &"nogaxeh_blast")
	Telemetry.event(&"detonation", {"amt": amount, "core": core,
			"hp": player.health.hp, "max_hp": player.health.max_hp})
	print("[fuse] detonated t=%.0fs core=%s dmg=%d hp=%d/%d"
			% [time_survived, core, amount, player.health.hp, player.health.max_hp])
	hud.announce("NOGAXEH DETONATES")
	Sfx.play(&"boss_death", 0.0)
	player.camera.add_trauma(1.2)
	_hitstop(0.16)
	_spawn_burst.call_deferred(at, Color(1.0, 0.85, 0.5), 6.0)


## A few frames of near-frozen time so the kill LANDS before the celebration
## starts. Engine.time_scale rather than tree pause, because pausing would also
## stop the tweens and particles that sell the moment. The timer runs on REAL
## time (last arg), or it would itself be slowed to a crawl by the effect.
##
## time_scale is reset in _ready as well: a scene reload mid-hitstop would
## otherwise leave the whole game running at 5% speed with no way back.
func _hitstop(seconds: float) -> void:
	# Composed with the speed toggle, never assigned absolutely. Two systems both
	# writing Engine.time_scale is how you end up permanently stuck at 0.05.
	Engine.time_scale = run_speed() * 0.05
	await get_tree().create_timer(seconds, true, false, true).timeout
	Engine.time_scale = run_speed()


## The current time multiplier. Single source of truth for anything that touches
## Engine.time_scale.
func run_speed() -> float:
	return SPEED_STEPS[_speed_index]


func _cycle_speed() -> void:
	_speed_index = (_speed_index + 1) % SPEED_STEPS.size()
	Engine.time_scale = run_speed()
	Sfx.play(&"click", -10.0)
	hud.announce("SPEED  x%d" % int(run_speed()))


func _on_gem_collected(xp_value: int) -> void:
	Sfx.play(&"pickup", -19.0)
	var gained: int = Progression.xp_gain(xp_value, player.stats.xp_mult)
	total_xp += gained
	xp_into_level += gained
	_check_level_up()


## Drains banked XP one level at a time. Loops rather than recursing so a single
## fat gem worth several levels resolves cleanly: we break to show each offer,
## and _on_upgrade_chosen re-enters to continue draining. Every exit path
## refreshes the HUD — the old version didn't, so chained level-ups left the XP
## bar stale until the next gem.
func _check_level_up() -> void:
	while xp_into_level >= Progression.xp_required(level):
		xp_into_level -= Progression.xp_required(level)
		var from_level: int = level
		level += 1
		_apply_level_drip()
		if not Progression.offers_card(level):
			# Two levels in three pass without a card. Still a beat — but until
			# now the ONLY signal was the level number ticking, and a playtester
			# reported "0 indication we are getting stat boosts when leveling
			# up". The drip is the majority of the run's power and it was
			# invisible, which makes a silent level read as nothing happening
			# rather than as a reward.
			Sfx.play(&"levelup", -15.0)
			hud.show_level_toast(level, Progression.drip_gains(from_level, level))
			continue
		var offers: Array[UpgradeResource] = pool.draw_tiered(
				3, stacks, _offer_gates(),
				Rarity.progress_for_level(level), _pity)
		_pity = 0 if pool.rolled_high else _pity + 1
		if offers.is_empty():
			continue  # everything maxed — bank the level, keep playing
		# Log what was OFFERED, not just what was taken: a pick rate without a
		# denominator says "common upgrades are popular", which is worthless.
		var offered_ids: Array[String] = []
		var offered_tiers: Array[int] = []
		for u: UpgradeResource in offers:
			offered_ids.append(String(u.id))
			offered_tiers.append(int(u.rarity))
		Telemetry.event(&"offer", {"lvl": level, "ids": offered_ids, "tiers": offered_tiers})
		if _dev_autopick:
			_on_upgrade_chosen.call_deferred(offers[0])
			break
		Sfx.play(&"levelup", -3.0)
		# Breadcrumb BEFORE the pause + panel build, so if this moment freezes the
		# marker is already flushed. Freeze #3 (2026-08-03, t=90-120s, LV~17, arena
		# near-empty) coincided with "I think I heard an audio cue" — and this is
		# the loud cue followed by a tree pause and a UI build. The line exists to
		# turn that hunch into evidence either way.
		print("[card] open t=%.0fs lvl=%d" % [time_survived, level])
		get_tree().paused = true
		level_up_panel.show_offers(offers, level)
		break
	hud.set_xp(xp_into_level, Progression.xp_required(level), level)


## Everything that can open a card: the profile's permanent unlocks AND the
## weapons drafted in THIS run. One list because the pool asks one question —
## "is this gate held?" — and Main is the only place that knows both halves.
##
## The distinction is the point of M7.3. A meta unlock puts a weapon's own draft
## card into the pool; drafting that card opens the weapon's branch of upgrades.
## Before this, a veteran saw orbital cards in every run whether or not the
## orbital was in it.
func _offer_gates() -> Array[StringName]:
	var gates: Array[StringName] = Meta.state.unlocks.duplicate()
	for id: StringName in player.stats.drafted_weapons:
		gates.append(UpgradeResource.weapon_gate(id))
	# ...and skill-tree purchases, whose node ids gate the shop-only cards. A
	# third kind of gate, still one array, because the pool only ever asks
	# whether a gate is held.
	gates.append_array(Meta.state.purchases)
	return gates


## Permanent bumps bought in the skill tree, applied to the base numbers this run
## starts from. Applied BEFORE Health is built from `stats.max_hp`, or a bought
## +2 max HP would show up in the pause screen and nowhere else.
##
## Every difficulty number in the game is tuned against a ZERO tree, so this can
## only ever make a run easier than its tuning target. That is the whole
## mitigation behind shipping a permanent stat tree next to a rebalance, and it
## is why the nodes are deliberately small.
func _apply_purchases() -> void:
	var hp_before: int = player.stats.max_hp
	for node: SkillNode in SkillList.ALL:
		if Meta.state.has_purchase(node.id):
			node.apply_to(player.stats)
	# Children are ready before their parent, so Player already built its Health
	# from the pre-purchase max_hp. Push the difference through rather than
	# rebuilding Health, which would drop the signal connections with it.
	var gained: int = player.stats.max_hp - hp_before
	if gained > 0:
		player.health.raise_max(gained)
	player.refresh_from_stats()


func _apply_level_drip() -> void:
	player.stats.drip_damage_bonus = Progression.drip_damage_bonus(level)
	player.stats.drip_projectile_bonus = Progression.drip_projectiles(level)
	player.stats.drip_cooldown_mult = Progression.drip_cooldown_mult(level)
	player.stats.drip_move_speed_mult = Progression.drip_move_speed_mult(level)


func _on_upgrade_chosen(upgrade: UpgradeResource) -> void:
	# Closes the [card] bracket: open with no pick = froze on the card screen;
	# open + pick + silence = froze after resuming. Different suspects entirely.
	print("[card] pick t=%.0fs id=%s" % [time_survived, upgrade.id])
	Telemetry.event(&"pick", {"lvl": level, "id": String(upgrade.id),
			"tier": int(upgrade.rarity),
			"stack": int(stacks.get(upgrade.id, 0)) + 1})
	stacks[upgrade.id] = int(stacks.get(upgrade.id, 0)) + 1
	upgrade.apply_to(player.stats)
	# Two effects touch live Health, which Stats can't know about:
	match upgrade.effect:
		UpgradeResource.Effect.MAX_HP:
			player.health.raise_max(int(upgrade.magnitude))
		UpgradeResource.Effect.HEAL:
			player.health.heal(int(upgrade.magnitude))
	player.refresh_from_stats()
	get_tree().paused = false
	_check_level_up()  # banked XP can trigger another level immediately


## The ONE place a run ends. Death used to be the only exit that banked anything:
## a restart, a quit to title or a closed window dropped both the telemetry
## ending row and the run's records. That is how a 2780-kill run left
## `best_kills` at 1125 — the player never died, they restarted.
func _finish_run(reason: String) -> void:
	if _ended:
		return
	_ended = true
	Telemetry.end_run(reason, {"kills": kills, "lvl": level, "won": run_state.won})
	# A run banked at victory only improves its records; absorbing again would
	# count the same run twice.
	if _banked:
		Meta.update_records(run_state.to_result())
	else:
		Meta.absorb_run(run_state.to_result())


## Restart, quit to title and closing the window all land here — four different
## scripts call reload_current_scene/change_scene_to_file, so the teardown is the
## only hook that catches every one of them without wiring a signal through each.
func _exit_tree() -> void:
	# Every DELIBERATE way out of a run prints this; a freeze that has to be
	# killed cannot. So a log whose last line is anything else IS a freeze, and
	# the line before it says when. Removes the ambiguity between "froze while
	# paused" and "paused, then quit" that [pause] alone would leave.
	print("[exit] t=%.0fs kills=%d lvl=%d" % [time_survived, kills, level])
	# Exit propagates children-first, so the HUD has already left the tree: a
	# banking unlock would try to tween on an exited node. Drop the announcement
	# before banking — at death the tree is intact and this never runs.
	if Meta.unlocked.is_connected(_on_unlocked):
		Meta.unlocked.disconnect(_on_unlocked)
	_finish_run("abandon")


func _on_player_died() -> void:
	# The other end-of-run marker. A freeze report whose log ends in [run_end]
	# froze on the game-over screen, not in the arena — different suspects.
	print("[run_end] t=%.0fs kills=%d lvl=%d by=%s src=%s"
			% [time_survived, kills, level, player.last_hit_by, player.last_hit_source])
	Telemetry.event(&"death", {"kills": kills, "lvl": level})
	_finish_run("death")
	Sfx.play(&"death")
	get_tree().paused = true
	# Computed rather than read back off MetaState: _finish_run has already added
	# it to the balance, so the difference is the only place the run's own share
	# still exists.
	var earned: int = maxi(0, MetaState.shards_for(time_survived, run_state.boss_events)
			- run_state.shards_banked)
	game_over.show_results(time_survived, kills, level,
			player.last_hit_by, player.last_hit_source, _new_unlocks, earned)
